-- Admin-managed external links (name + URL)
-- Run in Supabase SQL Editor

create table if not exists public.admin_links (
  id bigint generated by default as identity not null,
  name text not null,
  url text not null,
  created_at timestamp with time zone null default now(),
  constraint admin_links_pkey primary key (id),
  constraint admin_links_name_check check (char_length(trim(name)) > 0),
  constraint admin_links_url_check check (char_length(trim(url)) > 0)
) tablespace pg_default;

create index if not exists admin_links_name_idx on public.admin_links (name);
create index if not exists admin_links_created_at_idx on public.admin_links (created_at desc);

alter table public.admin_links disable row level security;

grant select, insert, update, delete on public.admin_links to anon, authenticated;
