-- All Projects Monitoring spreadsheet (run in Supabase SQL Editor after profiles.sql)

create table if not exists public.all_projects_monitoring (
  id bigint generated by default as identity not null,
  project_no text null,
  year integer null,
  municipality text null,
  project_type text null,
  firm text null,
  total_amount numeric(15, 2) null,
  downloaded_funds_to_beneficiary numeric(15, 2) null,
  project_title text not null,
  proponent text null,
  start_date date null,
  end_date date null,
  extension_request_3mo date null,
  extension_date date null,
  realignment_1st boolean not null default false,
  realignment_2nd boolean not null default false,
  intervention_equipment boolean not null default false,
  intervention_mooe boolean not null default false,
  intervention_trainings boolean not null default false,
  intervention_consultancy boolean not null default false,
  intervention_pl boolean not null default false,
  intervention_lab_others boolean not null default false,
  liquidation_psto boolean not null default false,
  received_approved boolean not null default false,
  lddap_date date null,
  moa_date date null,
  rtec_date date null,
  cash_program text null,
  status_report_1st boolean not null default false,
  status_report_2nd boolean not null default false,
  terminal_report boolean not null default false,
  completed boolean not null default false,
  terminated boolean not null default false,
  condonation boolean not null default false,
  with_letter_of_extension boolean not null default false,
  donated boolean not null default false,
  impact_assessment boolean not null default false,
  par_no text null,
  ptr_no text null,
  remarks text null,
  with_coo boolean not null default false,
  google_drive_links text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint all_projects_monitoring_pkey primary key (id),
  constraint all_projects_monitoring_project_type_check check (
    project_type is null
    or project_type = any (
      array[
        'GIA'::text,
        'SETUP'::text,
        'CEST'::text,
        'SSCP'::text
      ]
    )
  )
) tablespace pg_default;

create index if not exists all_projects_monitoring_year_idx
  on public.all_projects_monitoring (year);

create index if not exists all_projects_monitoring_project_no_idx
  on public.all_projects_monitoring (project_no);

alter table public.all_projects_monitoring disable row level security;

grant select, insert, update, delete on public.all_projects_monitoring to anon, authenticated;

-- Migration for existing databases (run alter_add_municipality_project_type.sql):
-- Adds municipality and project_type (GIA, SETUP, CEST, SSCP).
--
-- Migration for existing databases (run alter_extension_request_3mo_to_date.sql):
-- Converts extension_request_3mo from boolean NOT NULL to nullable date.
--
-- Migration for existing databases (run alter_drop_realignment_approved.sql):
-- Drops realignment_approved; 1st/2nd checks are under the realignment group only.
