-- Contacts directory (name, email, mobile, telephone, category)
-- Run in Supabase SQL Editor

create table if not exists public.contacts (
  id bigint generated by default as identity not null,
  name text not null,
  email text null,
  mobile_number text null,
  telephone_number text null,
  category text not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint contacts_pkey primary key (id),
  constraint contacts_name_check check (char_length(trim(name)) > 0),
  constraint contacts_category_check check (char_length(trim(category)) > 0)
) tablespace pg_default;

create index if not exists contacts_name_idx on public.contacts (name);
create index if not exists contacts_category_idx on public.contacts (category);
create index if not exists contacts_created_at_idx on public.contacts (created_at desc);

alter table public.contacts disable row level security;

grant select, insert, update, delete on public.contacts to anon, authenticated;
