-- In-app notifications (e.g. admin follow-up on overdue tasks)
-- Run in Supabase SQL Editor after profiles.sql and tasks.sql

create table if not exists public.notifications (
  id bigint generated by default as identity not null,
  recipient_id bigint not null,
  task_id bigint null,
  type text not null default 'task_follow_up'::text,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamp with time zone null default now(),
  constraint notifications_pkey primary key (id),
  constraint notifications_recipient_id_fkey foreign key (recipient_id)
    references public.profiles (id) on delete cascade,
  constraint notifications_task_id_fkey foreign key (task_id)
    references public.tasks (id) on delete set null
) tablespace pg_default;

create index if not exists notifications_recipient_id_idx
  on public.notifications using btree (recipient_id);

create index if not exists notifications_recipient_unread_idx
  on public.notifications using btree (recipient_id, is_read)
  where (is_read = false);

alter table public.notifications disable row level security;

grant select, insert, update, delete on public.notifications to anon, authenticated;

-- Real-time delivery to users (required for instant follow-up alerts)
alter publication supabase_realtime add table public.notifications;