-- PSTO org chart entries (name, position, responsibilities, photo, reporting line)
-- Run in Supabase SQL Editor (safe to re-run)

create table if not exists public.org_chart (
  id bigint generated by default as identity not null,
  name text not null,
  position text not null,
  responsibilities text null,
  employment_type text not null default 'regular',
  photo_url text null,
  parent_id bigint null,
  sort_order integer not null default 0,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint org_chart_pkey primary key (id),
  constraint org_chart_name_check check (char_length(trim(name)) > 0),
  constraint org_chart_position_check check (char_length(trim(position)) > 0),
  constraint org_chart_employment_type_check check (
    employment_type = any (array['regular'::text, 'contractual'::text])
  ),
  constraint org_chart_parent_id_fkey foreign key (parent_id)
    references public.org_chart (id) on delete set null
) tablespace pg_default;

-- Columns added after the first release
alter table public.org_chart add column if not exists photo_url text null;
alter table public.org_chart add column if not exists parent_id bigint null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_parent_id_fkey'
  ) then
    alter table public.org_chart
      add constraint org_chart_parent_id_fkey foreign key (parent_id)
      references public.org_chart (id) on delete set null;
  end if;
end $$;

create index if not exists org_chart_name_idx on public.org_chart (name);
create index if not exists org_chart_employment_type_idx on public.org_chart (employment_type);
create index if not exists org_chart_parent_id_idx on public.org_chart (parent_id);
create index if not exists org_chart_sort_order_idx on public.org_chart (sort_order);

alter table public.org_chart disable row level security;

grant select, insert, update, delete on public.org_chart to anon, authenticated;

-- Public bucket for personnel photos
insert into storage.buckets (id, name, public)
values ('org-chart-photos', 'org-chart-photos', true)
on conflict (id) do nothing;
