-- PSTO org chart canvas (personnel cards, free text, and lines)
-- Run in Supabase SQL Editor (safe to re-run)

create table if not exists public.org_chart (
  id bigint generated by default as identity not null,
  element_type text not null default 'person',
  name text null,
  position text null,
  responsibilities text null,
  employment_type text not null default 'regular',
  photo_url text null,
  parent_id bigint null,
  from_id bigint null,
  to_id bigint null,
  sort_order integer not null default 0,
  pos_x double precision null,
  pos_y double precision null,
  width double precision null,
  height double precision null,
  text_content text null,
  font_size integer null,
  color text null,
  has_arrow boolean not null default false,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint org_chart_pkey primary key (id),
  constraint org_chart_parent_id_fkey foreign key (parent_id)
    references public.org_chart (id) on delete set null,
  constraint org_chart_from_id_fkey foreign key (from_id)
    references public.org_chart (id) on delete cascade,
  constraint org_chart_to_id_fkey foreign key (to_id)
    references public.org_chart (id) on delete cascade
) tablespace pg_default;

-- Columns added after earlier releases
alter table public.org_chart add column if not exists photo_url text null;
alter table public.org_chart add column if not exists parent_id bigint null;
alter table public.org_chart add column if not exists element_type text not null default 'person';
alter table public.org_chart add column if not exists pos_x double precision null;
alter table public.org_chart add column if not exists pos_y double precision null;
alter table public.org_chart add column if not exists width double precision null;
alter table public.org_chart add column if not exists height double precision null;
alter table public.org_chart add column if not exists text_content text null;
alter table public.org_chart add column if not exists font_size integer null;
alter table public.org_chart add column if not exists color text null;
alter table public.org_chart add column if not exists has_arrow boolean not null default false;
alter table public.org_chart add column if not exists from_id bigint null;
alter table public.org_chart add column if not exists to_id bigint null;

-- Text and line elements carry no name/position
alter table public.org_chart alter column name drop not null;
alter table public.org_chart alter column position drop not null;
alter table public.org_chart drop constraint if exists org_chart_name_check;
alter table public.org_chart drop constraint if exists org_chart_position_check;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_parent_id_fkey'
  ) then
    alter table public.org_chart
      add constraint org_chart_parent_id_fkey foreign key (parent_id)
      references public.org_chart (id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_from_id_fkey'
  ) then
    alter table public.org_chart
      add constraint org_chart_from_id_fkey foreign key (from_id)
      references public.org_chart (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_to_id_fkey'
  ) then
    alter table public.org_chart
      add constraint org_chart_to_id_fkey foreign key (to_id)
      references public.org_chart (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_element_type_check'
  ) then
    alter table public.org_chart
      add constraint org_chart_element_type_check check (
        element_type = any (array['person'::text, 'text'::text, 'line'::text])
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_person_fields_check'
  ) then
    alter table public.org_chart
      add constraint org_chart_person_fields_check check (
        element_type <> 'person'
        or (
          char_length(trim(coalesce(name, ''))) > 0
          and char_length(trim(coalesce(position, ''))) > 0
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'org_chart_employment_type_check'
  ) then
    alter table public.org_chart
      add constraint org_chart_employment_type_check check (
        employment_type = any (array['regular'::text, 'contractual'::text])
      );
  end if;
end $$;

create index if not exists org_chart_name_idx on public.org_chart (name);
create index if not exists org_chart_element_type_idx on public.org_chart (element_type);
create index if not exists org_chart_employment_type_idx on public.org_chart (employment_type);
create index if not exists org_chart_parent_id_idx on public.org_chart (parent_id);
create index if not exists org_chart_from_id_idx on public.org_chart (from_id);
create index if not exists org_chart_to_id_idx on public.org_chart (to_id);
create index if not exists org_chart_sort_order_idx on public.org_chart (sort_order);

alter table public.org_chart disable row level security;

grant select, insert, update, delete on public.org_chart to anon, authenticated;

-- Public bucket for personnel photos
insert into storage.buckets (id, name, public)
values ('org-chart-photos', 'org-chart-photos', true)
on conflict (id) do nothing;
