-- Users stored in Table Editor only (no Supabase Authentication)
-- Safe to re-run

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

-- Uncomment once if you need a fresh table, then comment again:
-- drop table if exists public.profiles;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  code_name text not null,
  password text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz default now()
);

alter table public.profiles
  add column if not exists password text;

alter table public.profiles
  add column if not exists code_name text;

-- If old rows exist without password, set a placeholder before making NOT NULL:
-- update public.profiles set password = 'changeme' where password is null;
-- alter table public.profiles alter column password set not null;

drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

alter table public.profiles disable row level security;

grant select, insert, update, delete on public.profiles to anon, authenticated;
