-- Project monitoring (spreadsheet-style: project header + timeline logs)
-- Run in Supabase SQL Editor after profiles.sql

-- Projects under SETUP, GIA, SSCP, or CEST
create table if not exists public.monitoring_projects (
  id bigint generated by default as identity not null,
  program text not null,
  title text not null,
  location text null,
  created_by bigint null,
  created_at timestamp with time zone null default now(),
  constraint monitoring_projects_pkey primary key (id),
  constraint monitoring_projects_created_by_fkey foreign key (created_by)
    references public.profiles (id) on delete set null,
  constraint monitoring_projects_program_check check (
    program = any (
      array[
        'SETUP'::text,
        'GIA'::text,
        'SSCP'::text,
        'CEST'::text
      ]
    )
  )
) tablespace pg_default;

create index if not exists monitoring_projects_program_idx
  on public.monitoring_projects using btree (program) tablespace pg_default;

-- Timeline logs per project (DATE, REMARKS, PHOTOS)
create table if not exists public.project_timeline_entries (
  id bigint generated by default as identity not null,
  project_id bigint not null,
  entry_date date not null,
  remarks text null,
  photo_url text null,
  created_at timestamp with time zone null default now(),
  constraint project_timeline_entries_pkey primary key (id),
  constraint project_timeline_entries_project_id_fkey foreign key (project_id)
    references public.monitoring_projects (id) on delete cascade
) tablespace pg_default;

create index if not exists project_timeline_entries_project_id_idx
  on public.project_timeline_entries using btree (project_id) tablespace pg_default;

create index if not exists project_timeline_entries_entry_date_idx
  on public.project_timeline_entries using btree (entry_date) tablespace pg_default;

alter table public.monitoring_projects disable row level security;
alter table public.project_timeline_entries disable row level security;

grant select, insert, update, delete on public.monitoring_projects to anon, authenticated;
grant select, insert, update, delete on public.project_timeline_entries to anon, authenticated;

-- Migrate from old flat project_timelines table (if it exists)
do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'project_timelines'
  ) then
    insert into public.monitoring_projects (program, title, location, created_by, created_at)
    select distinct on (program, title)
      program,
      title,
      null,
      created_by,
      created_at
    from public.project_timelines
    order by program, title, created_at;

    insert into public.project_timeline_entries (project_id, entry_date, remarks, photo_url, created_at)
    select
      mp.id,
      pt.entry_date,
      pt.remarks,
      pt.photo_url,
      pt.created_at
    from public.project_timelines pt
    join public.monitoring_projects mp
      on mp.program = pt.program
     and mp.title = pt.title;

    drop table public.project_timelines;
  end if;
end $$;

-- Photo storage (run once)
insert into storage.buckets (id, name, public)
values ('project-timeline-photos', 'project-timeline-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public read project timeline photos" on storage.objects;
drop policy if exists "Anon insert project timeline photos" on storage.objects;
drop policy if exists "Anon update project timeline photos" on storage.objects;
drop policy if exists "Anon delete project timeline photos" on storage.objects;

create policy "Public read project timeline photos"
  on storage.objects for select
  using (bucket_id = 'project-timeline-photos');

create policy "Anon insert project timeline photos"
  on storage.objects for insert
  with check (bucket_id = 'project-timeline-photos');

create policy "Anon update project timeline photos"
  on storage.objects for update
  using (bucket_id = 'project-timeline-photos');

create policy "Anon delete project timeline photos"
  on storage.objects for delete
  using (bucket_id = 'project-timeline-photos');
