-- Tasks linked to profiles (person responsible)
-- Run in Supabase SQL Editor after profiles.sql

create table if not exists public.tasks (
  id bigint generated by default as identity not null,
  task_date date not null,
  agenda text not null,
  activities text not null,
  deadline date not null,
  deadline_time time without time zone null,
  responsible_id bigint not null,
  status text not null default 'pending'::text,
  program text not null default 'Other'::text,
  is_priority boolean not null default false,
  remarks text null,
  created_at timestamp with time zone null default now(),
  constraint tasks_pkey primary key (id),
  constraint tasks_responsible_id_fkey foreign key (responsible_id)
    references public.profiles (id) on delete restrict,
  constraint tasks_status_check check (
    status = any (
      array[
        'pending'::text,
        'ongoing'::text,
        'completed'::text,
        'on_hold'::text
      ]
    )
  )
) tablespace pg_default;

create index if not exists tasks_responsible_id_idx on public.tasks (responsible_id);
create index if not exists tasks_task_date_idx on public.tasks (task_date);

-- Optional time portion for `deadline`
alter table public.tasks
  add column if not exists deadline_time time without time zone null;

alter table public.tasks disable row level security;

grant select, insert, update, delete on public.tasks to anon, authenticated;

-- Migration for existing databases (run in Supabase SQL Editor):
-- alter table public.tasks
--   add column if not exists is_priority boolean not null default false;
-- alter table public.tasks
--   add column if not exists program text not null default 'Other'::text;
